server:
    port: 8091

spring:
    application:
        name: shop
    datasource:
        url: jdbc:postgresql://localhost:5432/seafood_shop_dev
        username: postgres
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        virtual-host: /
    cloud:
        consul:
            config:
                prefix: config
                format: yaml
                default-context: defaults
                data-key: application.yml
    amqp:
        exchange:
            attempts: 3


# security.yml
application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

