server:
    port: 8082

spring:
    data:
        mongodb:
            uri: mongodb+srv://soriano:lilo@inventory.b2y0lls.mongodb.net/inventory
    config:
        import: optional:consul:localhost:8500
    application:
        name: inventory
    datasource:
        url: jdbc:postgresql://localhost:5432/seafood_inventory_dev
        username: postgres
        password: lilo
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        virtual-host: /
    cloud:
        consul:
            config:
                prefix: config
                format: yaml
                default-context: defaults
                data-key: application.yml
                enabled: true
    amqp:
        exchange:
            attempts: 3

    messages:
        basename: i18n/messages


logging:
    level:
        com.fishtore.inventory.staticinventory: INFO

# security.yml
application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

