server:
    port: 8000

spring:
  application:
    name: gateway
  config:
    import: "optional:consul:"
  cloud:
    loadbalancer:
      ribbon:
        #Not needed since we excluded the dependency
        enabled: false
    consul:
      enabled: true
      discovery:
        # Get only services that are passing the health check
        query-passing: true
        #From the legacy bootstrap.yml
      config:
        data-key: application.yml
        prefix: config
        format: yaml
        default-context: defaults
    gateway:
      routes:
        - id: management # removed!
          uri: lb://management/
          predicates: # - Path=/api/{segment:boats,sellers}
            #- Path=/api/{segment}
            - Path=/api/sellers,/api/boats
        - id: store #changed to shop...
          uri: lb://store/
          predicates:
            - Path=/api/stores,/api/stores/**,
        - id: buyer-management # ===================================================================
          uri: lb://buyer/
          predicates:
            - Path=/api/users/buyers/all,/api/users/buyers/create,/api/users/buyers/**
        - id: inventory
          uri: lb://inventory/
          predicates:
            - Path=/api/catches,/api/catches/**,/api/inventory/,/api/inventory/**
        - id: shop # ===================================================================
          uri: lb://shop/
          predicates:
            - Path=/api/shops/active,/api/shops/**,/api/shops/initialize
        - id: transaction # ===================================================================
          uri: lb://transaction/
          predicates:
            - Path=/api/transactions,/api/transactions/all,api/transactions/placeOrder, api/transactions/**
        - id: static-inventory # ===================================================================
          uri: lb://static-inventory/
          predicates:
            - Path=/api/inventory**,/api/inventory/prices,/api/inventory/prices/**
        - id: price # ===================================================================
          uri: lb://price/
          predicates:
            - Path=/api/prices**,/api/prices,
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
              #"http://localhost:3000" # react
              #"http://localhost:4200" # angular
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST

logging:
  level:
    #org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.predicate: trace #can change from trace to WARN
